services:
  qdrant:
    image: 'qdrant/qdrant:latest'
    container_name: qdrant_rag
    ports:
      - "6333:6333"
      - "6334:6334"
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - "./prometheus-config.yml:/etc/prometheus/prometheus.yml"
    networks:
      - spring-ai
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - 3000:3000
    networks:
      - spring-ai

networks:
  spring-ai:
    driver: bridge

volumes:
  grafana-storage:
